name 'poise-ruby-init'
maintainer 'Luis De Siqueira'
maintainer_email 'LouTheBrew@gmail.com'
license 'MIT'
description 'Installs/Configures poise-ruby-init'
long_description 'Installs/Configures poise-ruby-init'
version '0.1.2'

depends 'poise'
depends 'poise-ruby-build'
